#!/bin/bash
INTERFACE="enp3s0"
INTERFACE2="enp4s0"

sudo tc qdisc del dev $INTERFACE root
sudo tc qdisc del dev $INTERFACE root
sudo wondershaper clear $INTERFACE
sudo wondershaper clear $INTERFACE
paplay /home/mahatur/Utility/Door.ogg &
echo "All traffic controls cleared!"
